name: pull-request-check
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        cypress-version: [10.0.0, 11.0.0, 12.0.0]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install NPM dependencies for SUT
        run: npm install
      - name: Specify Cypress version based on testing strategy
        run: npm install cypress@${{ matrix.cypress-version }}
      - run: npm test